# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-27 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181027_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='public_key',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='public_key'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app',
            name='secrete_key',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='secrete_key'),
            preserve_default=False,
        ),
    ]
