# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-11 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notification_user', '0002_userconnectionfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconnectionfield',
            name='type',
            field=models.IntegerField(choices=[(1, 'Email'), (2, 'Google cloud message')], default=1),
        ),
        migrations.AddField(
            model_name='userconnectionfield',
            name='value',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000, verbose_name='value'),
            preserve_default=False,
        ),
    ]
