# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-11 11:25
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('notification_user', '0003_auto_20181011_0917'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userconnectionfield',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
