# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-11 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification_user', '0004_auto_20181011_1125'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userconnectionfield',
            managers=[
            ],
        ),
    ]
