# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_django', '0003_auto_20170313_1314'),
        ('notification_user', '0005_auto_20181011_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConnectionFCMDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fcm_django.FCMDevice')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notification_user.User')),
            ],
        ),
        migrations.AlterField(
            model_name='userconnectionfield',
            name='type',
            field=models.IntegerField(choices=[(1, 'Email')], default=1),
        ),
    ]
