# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_user', '0006_auto_20181020_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconnectionfield',
            name='type',
            field=models.IntegerField(choices=[(1, 'Email'), (2, 'Firebase')], default=1),
        ),
    ]
