# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification_user', '0007_auto_20181020_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconnectionfcmdevice',
            name='user',
        ),
        migrations.AddField(
            model_name='userconnectionfcmdevice',
            name='user_connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notification_user.UserConnectionField'),
        ),
    ]
